export default [
  {
    id: 12,
    name: 'Seat',
    type: 'misc',
    url: 'https://eastriverparkbikerental.com/images/bikes/Seat.jpg',
    hours: {
      '1 hour': 5,
      '2 hours': 10,
      '3 hours': 15,
      '5 hours': 15,
      'all day(8AM-8PM)': 15,
      '24 hours': 15,
    },
  },
  {
    id: 13,
    name: 'Trailer',
    type: 'misc',
    url: 'https://eastriverparkbikerental.com/images/bikes/Trailer.jpg',
    hours: {
      '1 hour': 12,
      '2 hours': 17,
      '3 hours': 22,
      '5 hours': 25,
      'all day(8AM-8PM)': 33,
      '24 hours': 45,
    },
  },
  {
    id: 14,
    name: 'Basket',
    type: 'misc',
    url: 'https://eastriverparkbikerental.com/images/bikes/Basket.jpg',
    hours: {
      '1 hour': 1,
      '2 hours': 1,
      '3 hours': 1,
      '5 hours': 1,
      'all day(8AM-8PM)': 1,
      '24 hours': 1,
    },
  },
  {
    id: 15,
    name: 'Tagalong',
    type: 'misc',
    url: 'https://eastriverparkbikerental.com/images/bikes/Tagalong.jpg',
    hours: {
      '1 hour': 15,
      '2 hours': 20,
      '3 hours': 25,
      '5 hours': 30,
      'all day(8AM-8PM)': 40,
      '24 hours': 69,
    },
  },
  {
    id: 16,
    name: 'Dropoff',
    type: 'misc',
    url: 'https://eastriverparkbikerental.com/images/bikes/Dropoff.jpg',
    hours: {
      '1 hour': 5,
      '2 hours': 5,
      '3 hours': 5,
      '5 hours': 5,
      'all day(8AM-8PM)': 5,
      '24 hours': 5,
    },
  },
  {
    id: 17,
    name: 'Insurance',
    type: 'misc',
    url: 'https://eastriverparkbikerental.com/images/bikes/Insurance.jpg',
    hours: {
      '1 hour': 2,
      '2 hours': 2,
      '3 hours': 2,
      '5 hours': 2,
      'all day(8AM-8PM)': 2,
      '24 hours': 2,
    },
  },
];
