
export const bikeMockData = {
  'Most Popular': [
    {
      id: 1,
      name: 'Adult',
      type: 'bikes',
      url: 'https://eastriverparkbikerental.com/images/bikes/Adult.jpg',
      hours: {
        '1 hour': 15,
        '2 hours': 20,
        '3 hours': 25,
        '5 hours': 30,
        'all day(8AM-8PM)': 40,
        '24 hours': 69,
      },
    },
    {
      id: 2,
      name: 'Child',
      type: 'bikes',
      url: 'https://eastriverparkbikerental.com/images/bikes/Child.jpg',
      hours: {
        '1 hour': 12,
        '2 hours': 17,
        '3 hours': 22,
        '5 hours': 25,
        'all day(8AM-8PM)': 33,
        '24 hours': 45,
      },
    },
    {
      id: 3,
      name: 'Tandem',
      type: 'bikes',
      url: 'https://eastriverparkbikerental.com/images/bikes/Tandem.jpg',
      hours: {
        '1 hour': 30,
        '2 hours': 40,
        '3 hours': 50,
        '5 hours': 60,
        'all day(8AM-8PM)': 80,
        '24 hours': 0,
      },
    },
    {
      id: 6,
      name: 'E-Bike',
      type: 'bikes',
      url: 'https://eastriverparkbikerental.com/images/bikes/E-Bike.jpg',
      hours: {
        '1 hour': 30,
        '2 hours': 40,
        '3 hours': 50,
        '5 hours': 60,
        'all day(8AM-8PM)': 80,
        '24 hours': 0,
      },
    },
  ],
  'More Options': [
    {
      id: 4,
      name: 'Road',
      type: 'bikes',
      url: 'https://eastriverparkbikerental.com/images/bikes/Road.jpg',
      hours: {
        '1 hour': 30,
        '2 hours': 40,
        '3 hours': 50,
        '5 hours': 60,
        'all day(8AM-8PM)': 80,
        '24 hours': 0,
      },
    },
    {
      id: 5,
      name: 'Mountain',
      type: 'bikes',
      url: 'https://eastriverparkbikerental.com/images/bikes/Mountain.jpg',
      hours: {
        '1 hour': 30,
        '2 hours': 40,
        '3 hours': 50,
        '5 hours': 60,
        'all day(8AM-8PM)': 80,
        '24 hours': 0,
      },
    },
    {
      id: 7,
      name: 'Elliptigo',
      type: 'bikes',
      url: 'https://eastriverparkbikerental.com/images/bikes/Elliptigo.jpg',
      hours: {
        '1 hour': 30,
        '2 hours': 40,
        '3 hours': 50,
        '5 hours': 60,
        'all day(8AM-8PM)': 80,
        '24 hours': 0,
      },
    },
    {
      id: 8,
      name: 'Tricycle',
      type: 'bikes',
      url: 'https://eastriverparkbikerental.com/images/bikes/Tricycle.jpg',
      hours: {
        '1 hour': 15,
        '2 hours': 20,
        '3 hours': 25,
        '5 hours': 30,
        'all day(8AM-8PM)': 40,
        '24 hours': 69,
      },
    },
  ],
  Specialties: [
    {
      id: 9,
      name: 'Snow',
      type: 'bikes',
      url: 'https://eastriverparkbikerental.com/images/bikes/Snow.jpg',
      hours: {
        '1 hour': 30,
        '2 hours': 40,
        '3 hours': 50,
        '5 hours': 60,
        'all day(8AM-8PM)': 80,
        '24 hours': 0,
      },
    },
    {
      id: 10,
      name: 'Electric-Hand',
      type: 'bikes',
      url: 'https://eastriverparkbikerental.com/images/bikes/Electric-Hand.jpg',
      hours: {
        '1 hour': 30,
        '2 hours': 40,
        '3 hours': 50,
        '5 hours': 60,
        'all day(8AM-8PM)': 80,
        '24 hours': 0,
      },
    },
    {
      id: 11,
      name: 'Hand',
      type: 'bikes',
      url: 'https://eastriverparkbikerental.com/images/bikes/Hand.jpg',
      hours: {
        '1 hour': 15,
        '2 hours': 20,
        '3 hours': 25,
        '5 hours': 30,
        'all day(8AM-8PM)': 40,
        '24 hours': 69,
      },
    },
  ],
};

export const hoursMockData = {
  '1 hour': 15,
  '2 hours': 20,
  '3 hours': 25,
  '5 hours': 30,
  'all day(8AM-8PM)': 40,
  '24 hours': 69,
};
